# Generated by Django 5.0.3 on 2024-04-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aula', '0004_rename_pessoa_pessoas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='nascimento',
            field=models.DateField(),
        ),
    ]
