# Generated by Django 5.0.3 on 2024-04-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aula', '0005_alter_pessoas_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='pais',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
